swagger: "2.0"
info:
  description: "This is the Idexcel Inc. Admin Service API Swagger Documentation"
  version: "1.0"
  title: "Admin Service API"
  termsOfService: "https://github.com/idexecldemo/admin-service"
  contact:
    email: "shreyas.ramanath@idexcel.net"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "localhost:8080"
basePath: "/api"
schemes:
- "http"

paths:
  /lenders:
    get:
      tags:
      - "Admin Service"
      summary: "Get all lenders"
      description: "gets all lenders from the database"
      produces:
      - "application/json"
      consumes:
      - "application/json"
      responses:
        200:
          description: "OK"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Lender"
        404:
          description: "No Lenders Present"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/NoLender"
    
    post:
      tags:
      - "Admin Service"
      summary: "Create a new lender for post"
      description: "If an entry already is present it will give conflict 409 error"
      produces:
      - "application/json"
      consumes:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "object for bank should be added"
        required: true
        schema:
         $ref: "#/definitions/Bank"
      responses:
        201:
          description: "CREATED"
        409:
          description: "CONFLICT"
        400:
          description:
            "BAD REQUEST(missing data)"
          
  /lenders/{lenderId}/:
    put:
      tags:
      - "Admin Service"
      summary: "Update an existing Lender by Id"
      description: "If the lender whose details are to be updated is not found, 404 error is thrown"
      produces:
      - "application/json"
      consumes:
      - "application/json"
      parameters:
      - name: lenderId
        in: path
        required: true
        description: "Update the details about a particular lender whose Id is specified in the url parameter"
        type: "integer"
        format: "int64"
      - in: "body"
        name: "body"
        description: "Updated the required lender"
        required: true
        schema: 
          $ref: "#/definitions/Lender"
      responses:
        204:
          description: "No Content"
        404:
          description: "Lender not found"
    
    get:
      tags:
      - "Admin Service"
      summary: "Get a particular lender by Id"
      description: "If lender not found with given Id, 404 error"
      produces:
      - "application/json"
      consumes:
      - "application/json"
      parameters:
      - name: "lenderId"
        in: "path"
        description: "Id of the lender who needs to be fetched"
        required: true
        type: "integer"
        format: "int64"
      responses:
        200: 
          description: "OK"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Lender"
        404:
          description: "NOT FOUND"
    
    delete:
      tags:
      - "Admin Service"
      summary: "Delete an existing Lender by Id"
      produces:
      - "application/json"
      consumes:
      - "application/json"
      parameters:
      - name: lenderId
        in: path
        required: true
        description: "Delete a lender based on Id specified in the Url parameter"
        type: "integer"
        format: "int64"
      responses:
        204:
          description: "No Content"
        404:
          description: "Not found"
    
    head:
      tags:
      - "Admin Service"
      summary: "Hit the Get API for lenders to check status but don't retrieve any JSON response"
      description: "Similar to GET but no response data"
      produces:
      - "application/json"
      consumes:
      - "application/json"
      parameters:
      - name: lenderId
        in: path
        required: true
        description: "Check health of the get API endpoint"
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "OK"
        204:
          description: "No Content"
        404:
          description: "Not found"
      
    
  /lenders/{lenderId}/status:
    patch:
      tags:
      - "Admin Service"
      summary: "Patches a Lender details by Id and status"
      description: "Multiple status values can be provided with comma separated strings"
      produces:
      - "application/json"
      consumes:
      - "application/json"
      parameters:
      - name: lenderId
        in: path
        description: "Status values that need to be considered for filter"
        required: true
        type: "array"
        items:
          type: "string"
      responses:
        204:
          description: "No Content"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/patchLenderStatus"
        404:
          description: "Not Found"

definitions:
  Lender:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      name:
        type: "string"
      address:
        $ref: "#/definitions/Address"
      status:
        type: "string"
      createdBy:
        type: "string"
        format: "date-time"
      updatedBy:
        type: "string"
  
  NoLender:
    type: "object"
  Bank:
    type: "object"
    properties:
      name:
        type: "string"
      address: 
        $ref: "#/definitions/Address"
          
    
  Address:
    type: "object"
    properties:
      street:
        type: "string"
      city:
        type: "string"
      state:
        type: "string"
      zipcode:
        type: "string"
      country:
        type: "string"
        
  patchLenderStatus:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      status:
        type: "string"
        